// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7VjJ6XXtXU_mHA1Oo_ZbQBv-EUHxzsRM',
    appId: '1:1067332443113:android:67b80e33990c93a7ccc978',
    messagingSenderId: '1067332443113',
    projectId: 'testing-cli-6f57b',
    databaseURL: 'https://testing-cli-6f57b-default-rtdb.firebaseio.com',
    storageBucket: 'testing-cli-6f57b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP-AQzscffvSf0PtAtj2XjhCxaiwHL3Ls',
    appId: '1:1067332443113:ios:d0a31512823f2c33ccc978',
    messagingSenderId: '1067332443113',
    projectId: 'testing-cli-6f57b',
    databaseURL: 'https://testing-cli-6f57b-default-rtdb.firebaseio.com',
    storageBucket: 'testing-cli-6f57b.appspot.com',
    iosBundleId: 'com.example.chatCallApp',
  );
}
